/*
* Generated file
*
* Generated from: yang module name: resourcemonitor-impl yang module local name: resourcemonitor-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Apr 17 16:39:12 BST 2018
*
* Do not modify this file unless it is present under src/main directory
*/
package eu.virtuwind.resourcemonitor.impl;
public interface ResourcemonitorModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

}
